name: M Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53801
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4e4'
    - '#000000'
    - '#737373'
    - '#d50016'
    - '#ff5100'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
