name: M Photography
favicon: null
layout_spectrum: 0.24708
typography_spectrum: 0.66945
title: '10:10 Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f4040'
    - '#040707'
    - '#929291'
    - '#e67425'
    - '#ffffff'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
