name: M Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51502
title: M Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f4040'
    - '#040707'
    - '#929291'
    - '#e67425'
    - '#ffffff'
  brandStrength: 0
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
